### ISSUE TITLE
ROADMAP Fadin 0.2 release

### ISSUE THREAD

**Issue by tomMoral** [mind-inria/FaDIn#17]
TODO before releasing Fadin 0.2

- [ ] Change API to feed in events as pd.DataFrame (PR #15 )
- [ ] Remove unused parameters from the API  (PR #16 )
- [ ] Add the possibility to learn with `marks`.
- [ ] Add UnHap solver (in a file `solvers/unhap.py`).
- [ ] Add examples for UnHap
- [ ] Decide if we change the name for the package.
